document.write('\
\
    <p><span class="bold">Assigned: Mon, Nov. 25, 2013; Due: Mon, Dec. 2, 2013 </span><span class="italic">(note: no late turn-ins for HW5!)</span></p>\
    <p>Each person will evaluate the user interfaces of two other people in the class. After you turn in your system for Homework 4, the TA will e-mail you the two systems you are to evaluate. You can also see the assignment of systems to people on Blackboard.</p>\
    <p>You will be getting two (2) systems. You should write a heuristic evaluation of the site using <a href="http://www.nngroup.com/articles/ten-usability-heuristics/" target="_blank">Neilsen\'s Ten Usability Heuristics</a>. (There are lots of different lists of heuristics, but for this assignment, <span class="italic">you must use only</span> the ones that <a href="http://www.nngroup.com/articles/ten-usability-heuristics/" target="_blank">Nielsen lists</a>). Although two people are assigned to evaluate each project. you should do the evaluation individually.</p>\
    <p>Perform a heuristic evaluation of the systems you have been assigned, and write a report using the <a href="http://www.cs.cmu.edu/~bam/uicourse/HE_Report_template.doc" target="_blank">HE Report template</a>. (see also the <a href="http://www.cs.cmu.edu/~bam/uicourse/HE_Report_template-Example-CDW.doc" target="_blank">partial example in doc</a> format).</p>\
    <ul>\
        <li>Your report can include both <span class="bold">problems</span> and <span class="bold">things done well</span>, but it is better to list problems.</li>\
        <li>You should include <span class="bold">pictures</span> of the system that illustrate each of your points (either directly in the "Prototype Screen" column as in the example, or below the table with a hyperlink reference, as in the template). You can use screen captures to do this (on a PC, the print screen key puts the screen on the clipboard; on a Mac, command-shift-4 let\'s you pick a selection on the screen to send to a file, command-control-shift-4 puts it on the clipboard).</li>\
        <li>Each point should be annotated with the particular <span class="bold">Name of Heuristic</span> that is being violated or being followed (put this in the "<span class="bold">Name of Heuristic</span>" slot). If violated, you might suggest a fix in the <span class="bold">Way(s) to rectify</span> column.</li>\
        <li>For each system you are assigned, you must list at least <span class="bold">8</span> (eight) points that illustrate at least <span class="bold">4</span> (four) different guidelines. I am looking for insight, subtlety and depth. Thus, saying "the system doesn\'t have good color choices because it doesn\'t use color" is pretty trivial and won\'t count for much. Also, since this is a prototype, saying that functions aren\'t implemented also doesn\'t count. For example, prototypes generally won\'t have "documentation and help" so it is not useful to point that out.</li>\
        <li>Be sure each row lists <span class="bold">which</span> heuristic is violated or upheld, and <span class="bold">why</span>, and what you recommend be done about it. Be sure it is clear in your description whether you are saying the interface violates the heuristic or does it well.</li>\
    </ul>\
    <p>You will be graded for this homework on how well you evaluate the prototype, the quality of the feedback you are providing, how many problems and good things you found, and the extent to which you assign them to the correct heuristics.</p>\
    <p>In homework 6, you will be trying to fix the problems that other people identified with your system, and your grade will be based in part on your <span class="italic">response</span> to your classmate\'s Heuristic Analysis of your prototype (what you did based on what they found), so it is important to you to make sure your classmate gets a chance to evaluate your prototype.</p>\
    <ul>\
        <li>The <span class="bold">deliverable</span> for this assignment are two HE Report templates filled out, one for each of the systems you evaluated. This will be at least 2 (systems) x 8 (items) = 16 items.</li>\
        <li>Please keep the documents as <span class="bold">two files</span>, so that we can email them to the people whose projects you evaluated. Please name your two files as follows: HE-Report-of-<span class="italic">otherPersonsName</span>-from-<span class="italic">yourname</span>. For example, if one of the systems I was evaluating was by Rebecca Chen, my file about that evaluation would be named: HE-Report-of-Chen-from-Myers.docx.</li>\
        <li>Collect all your files together into one zip file, and upload the one zip file named HCI-HW5-<span class="italic">lastname-firstname</span>.pdf to Blackboard, as described in the submitting instructions.</li>\
    </ul>\
');