document.write('\
\
    <p><span class="bold">Assigned: Wed, October 30, 2013;   Due: Wed, Nov. 6, 2013</bold></p>\
    <p>(See <a href="syllabus.html#submit">how to submit homeworks</a> -- in summary, you will submit on blackboard. See also the <a href="syllabus.html#grading">grading policies</a>.)</p>\
    <p>The device choices are on the GoogleDocs page (see Blackboard for a link to it)</p>\
    <p>Normally, for contextual inquiry, you would just go and watch users performing their tasks in their normal course of business or home life. However, that is not feasible for the devices we selected. Therefore, we have to use as close a substitute as possible:</p>\
    <h4>PART A:</h4>\
    <p>The first part of this assignment is to <span class="bold">describe one or more representative tasks</span> that users would perform with your device, that will exercise the parts of the device you want to create. You should come up with enough tasks that an expert doing all of them will take about 5 minutes to perform, and a novice would take about <span class="bold">15 minutes</span> (so they need to be somewhat complex). You must describe the tasks by the function and results and <span class="italic">not</span> by the steps to perform them. Therefore, the task descriptions should work <span class="italic">no matter what the user interface looks like</span>. For example, you might say "the clock should end up displaying the current time", rather than "push the HR and MIN buttons to set the time". You should also design a preliminary questionaire that asks about <span class="italic">why, when and how</span> the user does these kinds of tasks now, and any <span class="italic">influenceson</span> their decisions. You can ask these questions before, during or after the actual test activities.</p>\
    <ul>\
        <li>The deliverables for PART A are the <span class="bold">description of your device</span> (what kind of device and what parts of the interface to it), and</li>\
        <li>The <span class="bold">script of exactly what you will say</span> to instruct the users on which tasks they should achieve (remember, the instructions should tell them what to do, not how). This includes the questions you will ask initially to find out the context of why, when and how the user does these kinds of tasks now. Note that this script will have two parts - the preliminary interview questions, and then the specific instructions to perform the tasks.</li>\
    </ul>\
    <h4>PART B:</h4>\
    <p>Next, you will perform a <span class="bold">Contextual Inquiry</span> on one (1) user trying to perform your task(s) on an existing real device. Ideally, you would test multiple people with a variety of skill levels, but since we do not have time for that, you should pick one user who is not experienced with the device. Preferably, this should be a person who is <span class="bold">not at all familiar with this type of device, and will have a lot of trouble using it</span>. If you cannot find anyone who has trouble with the tasks, then you need to (1) find a user who is less skilled, (2) switch devices to something more complicated, and/or (3) invent harder tasks to perform and revise PART A. In general, elderly people tend to be less skilled with modern devices, so finding someone over 50 with little technical experience might be appropriate. It would not be surprising if your inexperienced user takes a long time to perform your tasks. If it looks like it will take more than an hour, then you probably want to provide some help.</p>\
    <p>You might want to videotape your session. Probably, most people can use the video recording on their phone, laptop or tablet. Another option if you are doing something on a computer (e.g., testing a web page) is to use <span class="italic">screen recording</span> and audio from the computer\'s microphone. Alternatively, almost everyone now has a phone that will record at least audio (on the iPhone, there are \"voice memos\" for example).</p>\
    <p>In performing the Contextual Inquiry, you should read your script from PART A, and record all the user\'s actions, preferably on video or audio.</p>\
    <ul>\
        <li>The deliverables for PART B will be a brief <span class="bold">description of the user</span> (note: not their name, but instead their experience and demographic properties), and</li>\
        <li>A <span class="bold">transcript of what the user did and said, and what you did and said</span>. If at some points you have to help the users, because they cannot figure out what to do, that must be included in your transcript. It is not necessary to write down every word that the user says, just what is interesting and useful. Be sure to write down all <span class="italic">actions</span> on the device, whether correct or wrong. Note: we do not want you to turn in your videotape or audiotape, just the written transcript. The transcript should have <span class="italic">line numbers or time codes</span> so you can refer to particular points in the transcript in part C below. (Note that Microsoft Word can do line numbering for you, which makes this pretty easy.)</li>\
    </ul>\
    <h4>PART C:</h4> \
    <p>Now construct <span class="bold">Contextual Analysis diagrams</span> from the transcript. This must include an <span class="bold">artifact model</span>, which might be an annotated photograph or photographs of the actual device (or just screenshots if it is a computerized application) showing the various buttons and screens that the user used. Annotate this with any breakdowns caused by the interface itself (e.g., if the user could not understand a label). You must also make a <span class="bold">flow model</span> showing the flow of information between the user and various parts of the interface. Include any breakdowns relevant to the information flow. Finally, create a <span class="bold">social model</span> (also called a "cultural model") showing any influences on why and how the user chose to use the device. Another kind of model is a <span class="bold">physical model</span>, which you are welcome to make if it seems useful. (We are not asking you to create a sequence model.) Each label on each model should reference the appropriate point in the transcript using a line number or timecode from your transcript for where each element on the models is found. See the lecture slides and textbook for examples.</p>\
    <ul>\
        <li>The deliverables for PART C are the three (or four) models, with their annotations. You can draw the models using any drawing tool you like, such as Visio, Illustrator or even PowerPoint. Or, if you are very neat, you can even just draw them by hand on paper and then scan them into the computer (however, we will deduct points if it is not legible).</li>\
        <li>Finally, make a list of \"do\'s\" and \"don\'t\'s" for the user interface of your device, that you learned as a result of this study, that will guide your alternative design for the device. All of the recommendations for \"don\'ts\" should clearly refer back to breakdowns you observed. All the \"do\'s\" should refer back to things the user did successfully that you want to retain in your design.</li>\
    </ul>\
    <p><span class="bold">Create an electronic version of your homework, preferably as a single PDF file, and upload it to Blackboard.</span></p>\
');