document.write('\
\
    <p><span class="bold">Assigned: Wed, Nov. 13, 2013; Due: Mon, Nov. 18, 2013</span></p>\
    <p>Using the paper prototype you created in Homework 2, you are now going to run a usability evaluation of that prototype with one or more real people (users), revise the paper prototype to try to fix any problems found, and then run one or more <span class="italic">additional</span> people on the revised version.</p>\
    <h4>Part A:</h4>\
    <p>The first part of this assignment is to perform a Usability Evaluation of the prototype you created for homework 2. You should put your paper prototype in front of at least one person. This should be a <span class="italic">different</span> user than you used for your CI in homework 1, and this person should also be a novice at your appliance. As with the CI, you might want to videotape your sessions. You might also use the camera and microphone built into many laptops to record the session. Another option if you are doing something on a computer (e.g., testing a web page) is to use <span class="bold">screen recording</span> and audio from the computer\'s microphone. Alternatively, almost everyone now has a phone that will record audio (on the iPhone, there are "voice memos" for example) or even video.</p>\
    <p>The deliverable for PART A is the usability evaluation template filled out for at least one user. See the template here: <a href="http://www.cs.cmu.edu/~bam/uicourse/UsabilityEvalReport_template.doc">http:/\/www.cs.cmu.edu/~bam/uicourse/UsabilityEvalReport_template.doc</a> (see also the <a href="http://www.cs.cmu.edu/~bam/uicourse/UsabilityEvalReport_Example.doc">partial example in doc format</a>). This includes:</p>\
    <ul>\
        <li>A description of your user (note: not their name, but instead their experience and demographic properties),</li>\
        <li>The <span class="bold">script</span> that you use to direct the users on what to do. If it is the same as previous assignments, please mention this, but go ahead and <span class="italic">include it again</span>, so we have everything in one place. Note that this must include <span class="italic">exactly what you say to the user</span>.</li>\
        <li>A <span class="bold">transcript or summary of what the user did and said, and what you did and said</span>. If at some points you have to help the users, because they cannot figure out what to do, that must be included in your transcript. It is not necessary to write down every word that the user says, just what is interesting and useful. Be sure to write down all actions on the device, whether correct or wrong. Note: we do <span class="italic">not</span> want you to turn in your videotape or audiotape, just the transcript.</li>\
        <li><span class="bold">At least five (5) rows</span> describing problems that the user had. <span class="bold">NOTE:</span> If the user does not have at least 5 problems that you can report, then you can go back and revise your tasks to make them harder, or to include more parts of the user interface for your device, so you can find more complex tasks, and then do another user. Alternatively, you can do a <span class="italic">second user</span> for PART A, and it will be OK if you find at least 5 different things to describe across <span class="italic">both users</span> (but you still need to get additional users for PART C below).</li>\
        <li>For the "Prototype Screen" column, you can either scan in a copy of the relevant screen and circle the relevant part, or maybe you can number the screens on the paper prototype you turn in (like put numbers on each screen), and then you can refer to that number in that column. Just make sure it is clear to the graders which part of which screen is being referenced for each issue.</li>\
        <li>Possible extra credit for doing extra users and finding more than 5 problems. Use one template form per user.</li>\
    </ul>\
    <h4>Part B:</h4>\
    <p>Next, you will modify your paper prototype from homework 2 to <span class="bold">try to fix the problems</span> you observed in your user study, as described in the last column of your <span class="bold">Usability Evaluation Feedback Analysis</span> section of your report for PART A.</p>\
    <ul>\
        <li>The deliverables for PART B is a copy of your <span class="italic">new</span> paper prototype. Again, make a scan of this version as you did for homework 1.</li>\
        <li>Also turn in a <span class="bold">summary of what you changed</span>. This should be a short description. You should reference back to the row number for each problem you fix from PART B, so it is clear which fix goes with which problem.</li>\
    </ul>\
    <h4>Part C:</h4>\
    <p>Next, you will do <span class="italic">another</span> usability evaluation template filled out for <span class="italic">at least one <span class="bold">different</span> user</span> using your revised prototype (from Part B). This user should also be a novice with your device, and, if possible, might be a <span class="italic">different kind of person (different demographics)</span> than your user for PART A. Use <span class="italic">another copy</span> of the same template as for part A: <a href="http://www.cs.cmu.edu/~bam/uicourse/UsabilityEvalReport_template.doc">http:/\/www.cs.cmu.edu/~bam/uicourse/UsabilityEvalReport_template.doc</a>. Again, this is a <span class="italic">different person</span>, also a novice (so you have at least 3 people you have used so far -- at least 1 for HW#1, plus at least 2 more for this homework). You should videotape this session too.</p>\
    <p>The deliverable for PART C is another copy of the usability evaluation template filled out. This includes:</p>\
    <ul>\
        <li>Hopefully, your script has not changed from PART A, but if you need to change the script, then fill in the <span class="bold">new script</span>. If the script is the same, then just say "same script as PART A" in this part of the usability-evaluation-report-template document.</li>\
        <li>Fill in the remaining parts of the template as for PART A. Since you have a different user for PART C, all of the rest of the information should be different as well.</li>\
        <li>For this user, you only need to fill in at least <span class="bold">two (2) rows</span> describing problems that the user had. Again, if you can\'t find 2 problems, then try a harder task, or yet another user.</li>\
        <li>Note that this time you do <span class="italic">not</span> need to change your interface from Part B to reflect the "Way(s) to rectify" column for the results of the Part C. Instead, you will be making an implementation of your revised design as part of Homework 4.</li>\
        <li>Possible extra credit for doing extra users. Use one template form per user.</li>\
    </ul>\
    <p>In summary, you will be turning in two (2) copies of the filled out <a href="http://www.cs.cmu.edu/~bam/uicourse/UsabilityEvalReport_template.doc">UsabilityEvalReport_template.doc</a> (one for PART A and one for PART C), a revised paper prototype (PART B), and a short discussion of what you changed in the new version of the prototype. Please turn in this assignment a single pdf or zip file of all your deliverables, and upload the one file to Blackboard.</p>\
');