document.write('\
\
    <p><span class="bold">Assigned: Mon, Nov. 18, 2013; Due: Mon, Nov. 25, 2013</span><span class="italic"> (note: no late turn-ins for HW4!)</span></p>\
    <p>Using the design that resulted from all your testing and revisions from Homework 3, you are now going to implement the interface. You can use any way to implement your prototype such as those that were discussed in class (see Lecture 7 which includes links to various places to download versions of the implementation tools).</p>\
    <h4>Part A:</h4>\
    <p>There is only one part to this assignment: to implement your interface. You should implement at least enough that all your user tasks can be completed, with sufficient feedback so the users can see what the system\'s responses are. You should <span class="italic">simulate</span> actions of your device. For example, if you were doing a copier, when the user clicks "Start" you might display a screen or dialog boxes that says everything about the current operation, for example: "now copying, 2-sided, no staples, using paper tray #1". If there are parts of your user interface you do not implement, there should still be controls (buttons, sliders, etc.) that would lead to those parts of the interface, but instead lead to screens or dialog boxes that say "not implemented yet" or something. That is, all of the screens you show should <span class="italic">look complete</span>, even if all the operations do not necessarily function. As another example, if you have a "search" button, it is fine if the search-results screen always shows the same thing, no matter what is searched for. As we have said a number of times, the complexity of the interface should be: "At least 30 “controls” (widgets: buttons, text fields).  About 10 different screens/pages/windows/modes".</p>\
    <p>Also create a short "readme.txt" file that describes what one can do with the prototype. This will guide the TAs on what is supposed to work. For example, tell what paths through your interface are working. If you pretended that the user searches for "aspirin", mention that kind of thing in the file. <span class="bold">The "readme.txt" file should also contain your task test script that you will use for the user test, so the TAs and others will know what you will tell users to do.</span> Put the readme.txt file in the top level folder where the implementation is so it will be at the top level of the .zip file.</p>\
    <ol>\
        <li>The deliverable for PART A is the complete implementation. If you have a web-based implementation, like for Balsamiq online, include the URL in the readme.txt file, and just turn in the readme file, but change the name to be <span class="bold">HCI-HW4-lastname-firstname.txt</span>. If you have a regular implementation, just zip up your entire directory structure including project files, the readme.txt file, etc. Name your file: <span class="bold">HCI-HW4-lastname-firstname.zip, for example: HCI-HW4-myers-brad.zip</span>. Put this file on blackboard in the Assignment 4 area. <span class="italic">NOTE: Make sure it will be easy for us to run your system, and to see the source code. Make sure any required images are included in the zip file, and include the "readme.txt" file explaining how to run your application.</span></li>\
    </ol>\
    <p>Important Notes:</p>\
    <ul>\
        <li>It must be easy for us to run your implementations. Note that it should be runnable on either a PC or a Mac. Points will be taken off if we have trouble making it run. Points will also be taken off if you forget to include your source code. It would be a good idea for you to test your zip file or URL on <span class="italic">another computer</span> to make sure you remembered everything.</li>\
        <li>Make sure all the pathnames (filenames) of any pictures or sound files you use are <span class="italic">relative</span> pathnames, so the project will run when it is moved to the TA\'s computer. For example, the filenames should not start with C:\ or file://c:/</li>\
        <li><span class="bold">We really need everyone to turn in this assignment on time, so we can give your final implementation to your classmates.</span></li>\
    </ul>\
');